Update yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -31,11 +31,18 @@ jobs:
 
       - name: Run tests with coverage
         run: |
-          pytest --cov=multiviewstacking --cov-report=xml --cov-report=term-missing
+          pytest --disable-warnings --cov=multiviewstacking --cov-report=xml --cov-report=term-missing
+
+      - name: Verify coverage file exists
+        run: |
+          echo "Listing coverage files..."
+          ls -lah .
+          test -f coverage.xml || (echo "X coverage.xml not found!" && exit 1)
 
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
         with:
+          token: ${{ secrets.CODECOV_TOKEN }}   # remove if public repo
           file: ./coverage.xml
           flags: unittests
           fail_ci_if_error: true
